#####################################################
################# EXPLANATION #######################
#
# This file and other configuration files are provided
# to create Hamilton specific functionality. While also
# providing interHamilton compatability for methods.
#
# This configuration file is used for deck loading.
# The Python script will read this file and, based
# on the volumes used for both plates and solutions,
# will autoload the deck for the Hamilton.
#
# This file is the lowest priority in the loading
# sequence. Thusly, this file is referenced when all 
# other deck loading protocols are exhausted.
#
#
#####################################################
#####################################################

VolumeEquations:
  200uL Biorad 96 Well PCR Plate:
    - SegmentNumber: 1
      MaxSegmentHeight: 11.5
      SegmentEquation: x * 6.5450
      
    - SegmentNumber: 2
      MaxSegmentHeight: 22.1
      SegmentEquation: x * 11
  
  400uL Thermo 96 Well PCR Plate:
    - SegmentNumber: 1
      MaxSegmentHeight: 11.5
      SegmentEquation: x * 6.5450
      
    - SegmentNumber: 2
      MaxSegmentHeight: 22.1
      SegmentEquation: x * 11

  1200uL DeepWell 96 Well PCR Plate:
    - SegmentNumber: 1
      MaxSegmentHeight: 11.5
      SegmentEquation: x * 6.5450
      
    - SegmentNumber: 2
      MaxSegmentHeight: 22.1
      SegmentEquation: x * 11
  
  Hamilton 1.5mL FlipTube:
    - SegmentNumber: 1
      MaxSegmentHeight: 11.5
      SegmentEquation: x * 6.5450
      
    - SegmentNumber: 2
      MaxSegmentHeight: 22.1
      SegmentEquation: x * 11

Dead Volume:
  200uL Biorad 96 Well PCR Plate: 25
  400uL Thermo 96 Well PCR Plate: 50
  1200uL DeepWell 96 Well PCR Plate: 100
  200uL Starstedt Tube Plate: 25
  2000uL Starstedt Tube Plate: 150
  2000uL Water Total Recovery Vial Plate: 50
  Hamilton 1.5mL FlipTube: 150
  15mL Centrifuge Tube: 500
  60mL Reagent Reservior: 2500
  200mL Reagent Trough: 6000

Steps:
  Incubate:
    LidHomeSequences:
      - Lid1_Home
      - Lid2_Home
    Heaters:
      COM_ID:
        - 1
        - 2
      Type:
        - HeaterShaker
        - HeaterShaker
      Shake:
        - True
        - True
      SequencePrefix:
        - _HHS1_
        - _HHS2_
      PlateSequences:
        96 Well PCR Plate:
          200: 96WellPCRPlate200uL
          400: 96WellPCRPlate400uL
          1200: 96WellPCRPlate1200uL
      LidSequences:
        96 Well PCR Plate:   
          200: Lid_200uL
          400: Lid_400uL
          1200: Lid_1200uL

  Transport:
    Lid:
      Open: 88
      Close: 81
    Vacuum:
      Open: 150
      Close: 150
    96 Well PCR Plate:
      200:
        Open: 85
        Close: 75
      400:
        Open: 85
        Close: 75
      1200:
        Open: 85
        Close: 73

  Desalt:
    Preferred Loading:
      Waste: 
        - Carrier38_Pos1_96WellPCRPlate1200uL_1mLChannel
      Buffer: 
        - T2
      Destination: 
        - Carrier38_Pos5_96WellPCRPlate1200uL_1mLChannel
    Type:
      SizeX:
        100:
          Total Buffer Volume: 1000

  Vacuum:
    Vacuum Sequences:
      Home: HomeSeq
      Vacuum: VacSeq

    PlateSequences:
      96 Well PCR Plate:
        200: Test
        400: Test2
        1200: Test3